// Generated by CoffeeScript 1.6.3
(function () {
    module.exports = {
        cookie_secret: 'secret_meteoric',
        serverPort: 9091,
        mysql: {
            database: 'test',
            host: '192.168.1.65',
            user: 'assist',
            password: 'ipcamera',
            port: 3306,
            multipleStatements: true
        },
        srbApi:"http://10.133.12.20:7810/wx_interface/SMSPOpeningInterfaceService.aspx",
        paySystem:"http://192.168.1.13:1366/Pay/api/",
        pointSystem_hbtb:"http://192.168.1.13:1225/api/PointSystem/"
    };
}).call(this);
